services:
  postgresdb:
    platform: linux/amd64
    image: postgres:15
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: on-failure
    image: public.ecr.aws/z7n4i8q5/accommodatonbookingservice-api:v01
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:${POSTGRES_DOCKER_PORT}/${POSTGRES_DATABASE}",
        "spring.datasource.username" : "${POSTGRES_USERNAME}",
        "spring.datasource.password" : "${POSTGRES_PASSWORD}",
        "spring.jpa.database-platform" : "org.hibernate.dialect.PostgreSQLDialect"
      }'
